title: gnehz972
subtitle: null
description: Android, Python, H5 technology study and share
author: gnehz972
language: zh-CN
timezone: Asia/Shanghai
url: https://ficusvirens.com
root: /
permalink: posts/:abbrlink/
permalink_defaults: null
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
include:
  - .well-known/*
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: null
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: HH:mm:ss
per_page: 10
pagination_dir: page
plugin:
  - hexo-generator-feed
feed: null
type: atom
path: atom.xml
limit: 20
theme: next
css:
  - /css/custom.css 
deploy:
  type: git
  repo: https://github.com/gnehz972/gnehz972.github.io.git
  branch: master
sitemap:
  url: https://ficusvirens.com
  path: sitemap.xml
abbrlink:
  alg: crc32
  rep: hex
html_minifier:
  enable: true
  ignore_error: false
  exclude: null
css_minifier:
  enable: true
  exclude:
    - '*.min.css'
js_minifier:
  enable: true
  mangle: true
  output: null
  compress: null
  exclude:
    - '*.min.js'
image_minifier:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
